### ISSUE TITLE
Expected to run on UI thread

### ISSUE THREAD

**Issue by HannanShaik** [ferrannp/react-native-sync-adapter#12]
Facing the error `Expected to run on UI thread`. When the task is running.

"react-native-sync-adapter": "^2.0.0",

**Dependencies:**
"react": "16.0.0-alpha.12",
"react-native": "0.48.1",

<img width="471" alt="screen shot 2017-12-13 at 5 24 32 pm" src="https://user-images.githubusercontent.com/1010745/33937724-8b833a72-e02a-11e7-8d94-19518de9f3c8.png">

Sometimes I am getting the error as `Object is not a function (evaluating 'taskProvider()(data)')`

Please help, I am struggling from past 2 days.
<img width="470" alt="screen shot 2017-12-13 at 5 15 51 pm" src="https://user-images.githubusercontent.com/1010745/33937588-19abd36e-e02a-11e7-8e33-660166510b60.png">

**Comment by HannanShaik** [comment]
@ferrannp Can you please help with this?

**Comment by ferrannp** [comment]
@HannanShaik I have not face such error but it looks like there is a related PR in react-native fixing it https://github.com/facebook/react-native/pull/15940.

So probably the best would be you try `react-native` version `0.50.0` or above.
