### ISSUE TITLE
Example not work

### ISSUE THREAD

**Issue by atomoc** [ferrannp/react-native-sync-adapter#18]
![screenshot_2018-10-21-11-14-42-969_com syncadapterexample](https://user-images.githubusercontent.com/465108/47264608-d3928780-d522-11e8-98c8-99834d20626d.png)

**Comment by atomoc** [comment]
All the same problem. When you click on SYNC NOW, the following is issued:
![screenshot_2018-10-21-11-30-30-686_com syncadapterexample](https://user-images.githubusercontent.com/465108/47264724-dd1cef00-d524-11e8-8ffa-17cb69a8858e.png)

**Comment by atomoc** [comment]
There is nothing interesting in the logs:
![2018-10-21 11-32-36](https://user-images.githubusercontent.com/465108/47264744-371db480-d525-11e8-9740-26cabebc60cb.png)

**Comment by atomoc** [comment]
I have been fighting for the third day trying to do at least some kind of background service, nothing happens. Is it something wrong with a smartphone?

**Comment by nestorgm** [comment]
I had same behaviour and message, then add to file strings.xml the line
<string name="rnsb_allow_foreground">true</string>
and it worked out on foreground. 
What i dont know yet is how to test it works on background, as nothing else happens.
