### ISSUE TITLE
Not working with react-native 0.61.2, HeadlessJsTaskConfig error

### ISSUE THREAD

**Issue by 28harishkumar** [ferrannp/react-native-sync-adapter#21]
In `react-native 0.60.2` HeadlessJsTaskConfig does not take null data. [SO answer](https://stackoverflow.com/a/59686204/4115953)

Code need to be modifed as follow:

```
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.bridge.Arguments;

.
.
WritableMap data = Arguments.createMap();

```

I can submit a PR if allow.

**Comment by mayankzen123** [comment]
@28harishkumar Is it working with android versions 9?

**Comment by 28harishkumar** [comment]
@mayankzen123 error is because [`Null`](https://github.com/facebook/react-native/blob/30491a208513451efa6c2a62a116c61b21363a22/ReactAndroid/src/main/java/com/facebook/react/jstasks/HeadlessJsTaskContext.java#L113) is passed here but [some WritableMap instance is expected](https://github.com/facebook/react-native/blob/30491a208513451efa6c2a62a116c61b21363a22/ReactAndroid/src/main/java/com/facebook/react/modules/appregistry/AppRegistry.java#L20). [This commit](https://github.com/facebook/react-native/commit/ac7ec4602fd4d8ec033a084df6a92437ea2d3a8a#diff-5494d461a49bd6bfdf5f0442cd9bd160) added `mData = source.mData.copy();` that breaks code when `Null` is passed. 

This has nothing to do with android version.
