### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by MuruganDurai** [ferrannp/react-native-sync-adapter#9]
The given example is not  logging anything ( or outputting"Headless JS task was fired!") at the chrome debug or "adb logcat" console, though the app is not running in the foreground (app closed). Could you please check this or if there is anything which I missed, let me know. Thanks.

Device : Moto E 1st Gen
OS: Android 5.1

PS: Wanted to use rn-sync-adapter to check location of the device every 3 mins in a production app

**Comment by botraunak** [comment]
I'm unable to see logs as well from the example. 
Going into settings -> Accounts -> sync now does show the `Headless JS task was fired` Log.

**Comment by ferrannp** [comment]
Ok, I am going to write better example (instead of logs that requires debugger) as part of #6, and I will be using system notifications. Let's keep track of this there.

**Comment by genaro10** [comment]
@ferrannp
![Captura de Pantalla 2021-11-23 a la(s) 13 13 59](https://user-images.githubusercontent.com/49800615/143061572-0cb06469-888c-45db-abcd-e56af6e8a92b.png)

Any help with this please?
